//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuseBeads.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrintResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrintResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuseBeads.Infrastructure.Resources.PrintResources", typeof(PrintResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbe.
        /// </summary>
        public static string PrintColorColumn {
            get {
                return ResourceManager.GetString("PrintColorColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbenliste.
        /// </summary>
        public static string PrintColorList {
            get {
                return ResourceManager.GetString("PrintColorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farben.
        /// </summary>
        public static string PrintColors {
            get {
                return ResourceManager.GetString("PrintColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        public static string PrintCountColumn {
            get {
                return ResourceManager.GetString("PrintCountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raster.
        /// </summary>
        public static string PrintGrid {
            get {
                return ResourceManager.GetString("PrintGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PrintNameColumn {
            get {
                return ResourceManager.GetString("PrintNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muster.
        /// </summary>
        public static string PrintPattern {
            get {
                return ResourceManager.GetString("PrintPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bügelperlen-Muster.
        /// </summary>
        public static string PrintTitle {
            get {
                return ResourceManager.GetString("PrintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perlen gesamt.
        /// </summary>
        public static string PrintTotalBeads {
            get {
                return ResourceManager.GetString("PrintTotalBeads", resourceCulture);
            }
        }
    }
}
