//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuseBeads.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuseBeads.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bügelperlen-Muster Generator.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Zurück.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bügelperlenmuster.
        /// </summary>
        public static string BeadPattern {
            get {
                return ResourceManager.GetString("BeadPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plattenraster.
        /// </summary>
        public static string BoardGrid {
            get {
                return ResourceManager.GetString("BoardGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helligkeit:.
        /// </summary>
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbe.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbenliste.
        /// </summary>
        public static string ColorList {
            get {
                return ResourceManager.GetString("ColorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farben.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrast:.
        /// </summary>
        public static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dithering.
        /// </summary>
        public static string Dithering {
            get {
                return ResourceManager.GetString("Dithering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden: {0}.
        /// </summary>
        public static string ErrorLoading {
            get {
                return ResourceManager.GetString("ErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim PDF-Export: {0}.
        /// </summary>
        public static string ErrorPdf {
            get {
                return ResourceManager.GetString("ErrorPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: {0}.
        /// </summary>
        public static string ErrorPrefix {
            get {
                return ResourceManager.GetString("ErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Drucken: {0}.
        /// </summary>
        public static string ErrorPrinting {
            get {
                return ResourceManager.GetString("ErrorPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Speichern: {0}.
        /// </summary>
        public static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📄 PDF.
        /// </summary>
        public static string ExportPdf {
            get {
                return ResourceManager.GetString("ExportPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raster.
        /// </summary>
        public static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildanpassungen.
        /// </summary>
        public static string ImageAdjustments {
            get {
                return ResourceManager.GetString("ImageAdjustments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 Leganleitung.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leganleitung.
        /// </summary>
        public static string InstructionTitle {
            get {
                return ResourceManager.GetString("InstructionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📂 Laden.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muster laden.
        /// </summary>
        public static string LoadPatternTitle {
            get {
                return ResourceManager.GetString("LoadPatternTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Farben:.
        /// </summary>
        public static string MaxColors {
            get {
                return ResourceManager.GetString("MaxColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originalbild.
        /// </summary>
        public static string OriginalImage {
            get {
                return ResourceManager.GetString("OriginalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bügelperlen-Designer.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette:.
        /// </summary>
        public static string Palette {
            get {
                return ResourceManager.GetString("Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📷 Bild auswählen.
        /// </summary>
        public static string PickImage {
            get {
                return ResourceManager.GetString("PickImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild auswählen.
        /// </summary>
        public static string PickImageTitle {
            get {
                return ResourceManager.GetString("PickImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🖨️ Drucken.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbe.
        /// </summary>
        public static string PrintColorColumn {
            get {
                return ResourceManager.GetString("PrintColorColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbenliste.
        /// </summary>
        public static string PrintColorList {
            get {
                return ResourceManager.GetString("PrintColorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farben.
        /// </summary>
        public static string PrintColors {
            get {
                return ResourceManager.GetString("PrintColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        public static string PrintCountColumn {
            get {
                return ResourceManager.GetString("PrintCountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raster.
        /// </summary>
        public static string PrintGrid {
            get {
                return ResourceManager.GetString("PrintGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PrintNameColumn {
            get {
                return ResourceManager.GetString("PrintNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muster.
        /// </summary>
        public static string PrintPattern {
            get {
                return ResourceManager.GetString("PrintPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bügelperlen-Muster.
        /// </summary>
        public static string PrintTitle {
            get {
                return ResourceManager.GetString("PrintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perlen gesamt.
        /// </summary>
        public static string PrintTotalBeads {
            get {
                return ResourceManager.GetString("PrintTotalBeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↪ Wiederholen.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄 Aktualisieren.
        /// </summary>
        public static string Regenerate {
            get {
                return ResourceManager.GetString("Regenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reihe.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sättigung:.
        /// </summary>
        public static string Saturation {
            get {
                return ResourceManager.GetString("Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💾 Speichern.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bügelperlen-Muster als PDF.
        /// </summary>
        public static string SharePdfTitle {
            get {
                return ResourceManager.GetString("SharePdfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bügelperlen-Muster drucken.
        /// </summary>
        public static string SharePrintTitle {
            get {
                return ResourceManager.GetString("SharePrintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bügelperlen-Muster speichern.
        /// </summary>
        public static string ShareSaveTitle {
            get {
                return ResourceManager.GetString("ShareSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einkaufsliste.
        /// </summary>
        public static string ShareShoppingListTitle {
            get {
                return ResourceManager.GetString("ShareShoppingListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛒 Einkaufsliste.
        /// </summary>
        public static string ShoppingList {
            get {
                return ResourceManager.GetString("ShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortiert nach Anzahl.
        /// </summary>
        public static string SortedByCount {
            get {
                return ResourceManager.GetString("SortedByCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle ein Bild aus, um ein Bügelperlenmuster zu erstellen..
        /// </summary>
        public static string StatusInitial {
            get {
                return ResourceManager.GetString("StatusInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muster geladen: {0}×{1} = {2} Perlen.
        /// </summary>
        public static string StatusLoaded {
            get {
                return ResourceManager.GetString("StatusLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muster wird geladen....
        /// </summary>
        public static string StatusLoading {
            get {
                return ResourceManager.GetString("StatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muster erstellt: {0}×{1} = {2} Perlen, {3} Farben.
        /// </summary>
        public static string StatusPatternCreated {
            get {
                return ResourceManager.GetString("StatusPatternCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF erstellt..
        /// </summary>
        public static string StatusPdfCreated {
            get {
                return ResourceManager.GetString("StatusPdfCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF wird erstellt....
        /// </summary>
        public static string StatusPdfCreating {
            get {
                return ResourceManager.GetString("StatusPdfCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druckseite erstellt..
        /// </summary>
        public static string StatusPrinted {
            get {
                return ResourceManager.GetString("StatusPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druckseite wird erstellt....
        /// </summary>
        public static string StatusPrinting {
            get {
                return ResourceManager.GetString("StatusPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild wird verarbeitet....
        /// </summary>
        public static string StatusProcessing {
            get {
                return ResourceManager.GetString("StatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muster gespeichert..
        /// </summary>
        public static string StatusSaved {
            get {
                return ResourceManager.GetString("StatusSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muster wird gespeichert....
        /// </summary>
        public static string StatusSaving {
            get {
                return ResourceManager.GetString("StatusSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perlen gesamt.
        /// </summary>
        public static string TotalBeads {
            get {
                return ResourceManager.GetString("TotalBeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↩ Rückgängig.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breite:.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
